import Link from "next/link";
import { EmptyState } from "@/components/ui/empty-state";
import { getAuthenticatedContext } from "@/lib/auth/context";
import { documentKindLabels, expenseCategoryLabels } from "@/lib/expenses/labels";
import { listExpenseDocuments } from "@/lib/expenses/queries";
import { billingDocumentKindLabels } from "@/lib/invoicing/labels";
import { listBillingDocuments } from "@/lib/invoicing/queries";
import { formatEuroCents } from "@/lib/sales/calculations";
import { formatFrenchDate } from "@/lib/utils/format";

export default async function DocumentsPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const [query, { context }] = await Promise.all([searchParams, getAuthenticatedContext()]);
  if (!context.business) return null;
  const [{ documents, missing }, billingDocuments] = await Promise.all([listExpenseDocuments(context.business.id), listBillingDocuments(context.business.id)]);
  const search = typeof query.recherche === "string" ? query.recherche.toLocaleLowerCase("fr-FR") : "";
  const filteredExpenses = documents.filter((document) => (!query.type || document.kind === query.type) && (!query.categorie || document.category === query.categorie) && (!query.fournisseur || document.supplierName === query.fournisseur) && (!query.annee || document.createdAt.startsWith(String(query.annee))) && (!search || `${document.originalName} ${document.expenseReference} ${document.supplierName}`.toLocaleLowerCase("fr-FR").includes(search)));
  const filteredBilling = billingDocuments.filter((document) => (!query.annee || document.issuedOn.startsWith(String(query.annee))) && (!search || `${document.number} ${document.buyerName} ${document.saleReference}`.toLocaleLowerCase("fr-FR").includes(search)));
  const suppliers = Object.fromEntries(documents.flatMap((document) => document.supplierName ? [[document.supplierName, document.supplierName]] : []));
  return <>
    <header className="page-header"><div><p className="eyebrow">Bibliothèque privée</p><h1>Documents</h1><p>Documents clients générés à la demande et justificatifs fournisseurs privés.</p></div></header>
    <form className="expense-filters"><Select name="type" label="Type fournisseur" entries={documentKindLabels}/><Select name="fournisseur" label="Fournisseur" entries={suppliers}/><Select name="categorie" label="Catégorie" entries={expenseCategoryLabels}/><div className="field"><label htmlFor="annee">Année</label><input className="input" id="annee" name="annee" inputMode="numeric" defaultValue={query.annee as string}/></div><div className="field"><label htmlFor="recherche">Recherche</label><input className="input" id="recherche" name="recherche" defaultValue={search}/></div><button className="secondary-link">Filtrer</button></form>
    <section><div className="section-heading"><div><p className="eyebrow">Ventes</p><h2>Documents clients</h2></div></div><p>Les PDF de factures et d’avoirs sont régénérés uniquement depuis leurs snapshots immuables ; aucun lien Storage signé n’est nécessaire.</p>{filteredBilling.length === 0 ? <EmptyState title="Aucune facture ou avoir" description="Créez une facture depuis une vente validée."/> : <div className="document-grid">{filteredBilling.map((document) => <article className="card" key={document.id}><span className="document-icon">PDF</span><h3>{document.number}</h3><p>{billingDocumentKindLabels[document.kind]} · {formatFrenchDate(document.issuedOn)} · {formatEuroCents(document.totalInclTaxCents)}</p><p>{document.buyerName} · vente {document.saleReference}</p><div className="form-actions"><Link className="secondary-link" href={`/factures/${document.id}`}>Consulter</Link><a className="secondary-link" href={`/factures/${document.id}/pdf`}>Télécharger</a></div></article>)}</div>}</section>
    <section><div className="section-heading"><div><p className="eyebrow">Dépenses</p><h2>Justificatifs fournisseurs</h2></div></div><p>Les liens signés de ces justificatifs Storage expirent après une minute.</p>{filteredExpenses.length === 0 ? <EmptyState title="Aucun justificatif" description="Ajoutez un justificatif depuis une dépense."/> : <div className="document-grid">{filteredExpenses.map((document) => <article className="card" key={document.documentId}><span className="document-icon">{document.mimeType === "application/pdf" ? "PDF" : "IMG"}</span><h3>{document.originalName}</h3><p>{documentKindLabels[document.kind]} · {Math.ceil(document.sizeBytes / 1024)} Ko · {formatFrenchDate(document.createdAt.slice(0, 10))}</p><p><Link href={`/depenses/${document.expenseId}`}>{document.expenseReference}</Link> · {document.supplierName ?? "Sans fournisseur"} · {expenseCategoryLabels[document.category]}</p>{document.signedUrl && <a className="secondary-link" href={document.signedUrl} target="_blank" rel="noreferrer">Ouvrir</a>}</article>)}</div>}</section>
    <section className="missing-documents"><h2>Dépenses validées sans justificatif</h2>{missing.length === 0 ? <p>Aucune.</p> : missing.map((expense) => <Link key={expense.id} href={`/depenses/${expense.id}`}><strong>{expense.reference}</strong><span>{expense.description}</span></Link>)}</section>
  </>;
}
function Select({ name, label, entries }: { name: string; label: string; entries: Record<string, string> }) { return <div className="field"><label htmlFor={name}>{label}</label><select className="input" id={name} name={name}><option value="">Tous</option>{Object.entries(entries).map(([key, value]) => <option key={key} value={key}>{value}</option>)}</select></div>; }
