import Link from "next/link";
import { notFound } from "next/navigation";
import { SubmitButton } from "@/components/ui/submit-button";
import { getAuthenticatedContext } from "@/lib/auth/context";
import { issueCreditNoteAction } from "@/lib/invoicing/actions";
import { sumInvoiceCents } from "@/lib/invoicing/calculations";
import { billingCommercialStateLabels, billingCustomerKindLabels, billingDocumentKindLabels, billingOperationCategoryLabels } from "@/lib/invoicing/labels";
import { getBillingDocument } from "@/lib/invoicing/queries";
import { formatEuroCents } from "@/lib/sales/calculations";
import { formatFrenchDate } from "@/lib/utils/format";

export default async function InvoiceDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const [{ id }, query, { context }] = await Promise.all([params, searchParams, getAuthenticatedContext()]);
  if (!context.business) return null;
  const data = await getBillingDocument(context.business.id, id);
  if (!data) notFound();
  const { document, refunds } = data;
  const error = typeof query.erreur === "string" ? query.erreur : null;
  const message = query.message === "facture-emise" ? "Facture émise et définitivement numérotée." : query.message === "avoir-emis" ? "Avoir émis et enregistré." : null;
  const credited = sumInvoiceCents(document.credits.map((credit) => credit.totalInclTaxCents));
  const remaining = sumInvoiceCents([document.totalInclTaxCents, -credited]);
  return <>
    <Link className="back-link" href="/factures">← Factures</Link><header className="page-header"><div><p className="eyebrow">{billingDocumentKindLabels[document.kind]}</p><h1>{document.number}</h1><p>Émise le {formatFrenchDate(document.issuedOn)} · {billingCommercialStateLabels[document.commercialState]}</p></div><a className="button-link" href={`/factures/${document.id}/pdf`}>Télécharger le PDF</a></header>
    {message && <p className="form-message success" role="status">{message}</p>}{error && <p className="form-message" role="alert">{error}</p>}
    {document.kind === "credit_note" && <p className="form-message">Avoir relatif à la facture <Link href={`/factures/${document.originalInvoiceId}`}>{document.originalInvoiceNumber}</Link> du {document.originalInvoiceIssuedOn ? formatFrenchDate(document.originalInvoiceIssuedOn) : "—"}. Motif : {document.creditReason}</p>}
    <section className="sale-detail-grid"><article className="card"><h2>Client</h2><dl className="detail-list"><D t="Type" v={billingCustomerKindLabels[document.buyerKind]}/><D t="Nom" v={document.buyerName}/><D t="Adresse" v={document.buyerAddress ?? (document.buyerAddressOmitted ? "Omise à la demande du particulier" : "—")}/><D t="Adresse de facturation" v={document.buyerBillingAddress ?? "—"}/><D t="Adresse de livraison" v={document.buyerDeliveryAddress ?? "—"}/><D t="SIREN" v={document.buyerSiren ?? "—"}/><D t="TVA intracommunautaire" v={document.buyerVatNumber ?? "—"}/><D t="Bon de commande" v={document.purchaseOrderReference ?? "—"}/></dl></article><article className="card"><h2>Vendeur snapshoté</h2><p><strong>{document.issuerLegalNameSnapshot}</strong>{document.issuerTradeNameSnapshot && <><br/>{document.issuerTradeNameSnapshot}</>}<br/>{document.issuerAddressSnapshot}<br/>SIREN {document.issuerSirenSnapshot}<br/>SIRET {document.issuerSiretSnapshot}</p><p>{document.issuerRegistrationDetailsSnapshot}</p></article></section>
    <section className="card sale-items-detail"><h2>{billingOperationCategoryLabels[document.operationCategory]}</h2>{document.items.map((item) => <div className="item-detail" key={item.id}><span>{item.description} · {item.quantity} × {formatEuroCents(item.unitPriceExclTaxCents)}</span><strong>{document.kind === "credit_note" ? "− " : ""}{formatEuroCents(item.lineTotalExclTaxCents)}</strong></div>)}<dl className="detail-list totals-list"><D t="Sous-total HT" v={formatEuroCents(document.subtotalExclTaxCents)}/><D t="Livraison" v={formatEuroCents(document.shippingExclTaxCents)}/><D t="Remise" v={`− ${formatEuroCents(document.discountExclTaxCents)}`}/><D t="Total HT" v={formatEuroCents(document.totalExclTaxCents)}/><D t="TVA" v={formatEuroCents(document.vatCents)}/><D t={document.kind === "invoice" ? "Total TTC" : "Montant crédité"} v={`${document.kind === "credit_note" ? "− " : ""}${formatEuroCents(document.totalInclTaxCents)}`}/></dl><p>{document.vatExemptionMentionSnapshot}</p><p>Échéance : {formatFrenchDate(document.paymentDueOn)}</p></section>
    {document.buyerKind === "professional" && <section className="card"><h2>Conditions B2B snapshotées</h2>{[document.paymentTermsSnapshot, document.earlyPaymentDiscountTermsSnapshot, document.latePenaltyTermsSnapshot, document.recoveryIndemnitySnapshot].map((value, index) => value && <p key={index}>{value}</p>)}</section>}
    {document.kind === "invoice" && <section className="history-section"><h2>Avoirs associés</h2>{document.credits.length === 0 ? <p className="history-empty">Aucun avoir.</p> : document.credits.map((credit) => <Link className="payment-card" href={`/factures/${credit.id}`} key={credit.id}><strong>{credit.number} · − {formatEuroCents(credit.totalInclTaxCents)}</strong><span>{formatFrenchDate(credit.issuedOn)} · {credit.creditReason}</span></Link>)}<h2>Remboursements de la vente</h2>{refunds.length === 0 ? <p className="history-empty">Aucun remboursement.</p> : refunds.map((refund) => <div className="refund-row" key={refund.id}><p>{formatFrenchDate(refund.refundedOn)} · {formatEuroCents(refund.amountCents)} · {refund.reason} · {refund.linked ? "Lié à un avoir" : "Non lié"}</p>{!refund.linked && remaining > 0 && refund.amountCents <= remaining && <details><summary>Créer l’avoir correspondant</summary><form action={issueCreditNoteAction} className="form-stack compact-form"><input type="hidden" name="invoiceId" value={document.id}/><input type="hidden" name="linkedRefundId" value={refund.id}/><input type="hidden" name="amount" value={formatCentsInput(refund.amountCents)}/><div className="field"><label htmlFor={`refund-credit-reason-${refund.id}`}>Motif</label><textarea className="input" id={`refund-credit-reason-${refund.id}`} name="reason" required/></div><p className="dashboard-note">Montant prérempli : {formatEuroCents(refund.amountCents)}. L’avoir et le remboursement resteront deux opérations distinctes.</p><SubmitButton>Émettre l’avoir lié</SubmitButton></form></details>}</div>)}</section>}
    {document.kind === "invoice" && remaining > 0 && <details className="action-panel"><summary className="button">Créer un avoir</summary><form action={issueCreditNoteAction} className="form-stack"><input type="hidden" name="invoiceId" value={document.id}/><div className="form-grid"><div className="field"><label htmlFor="credit-amount">Montant de l’avoir</label><input className="input" id="credit-amount" name="amount" inputMode="decimal" defaultValue={formatCentsInput(remaining)} required/></div><div className="field"><label htmlFor="credit-refund">Remboursement facultatif</label><select className="input" id="credit-refund" name="linkedRefundId"><option value="">Aucun</option>{refunds.filter((refund) => !refund.linked && refund.amountCents <= remaining).map((refund) => <option key={refund.id} value={refund.id}>{formatFrenchDate(refund.refundedOn)} · {formatEuroCents(refund.amountCents)}</option>)}</select></div></div><div className="field"><label htmlFor="credit-reason">Motif</label><textarea className="input" id="credit-reason" name="reason" required/></div><p className="dashboard-note">L’avoir corrige la facture. Le remboursement représente le mouvement financier. Les deux opérations restent distinctes.</p><SubmitButton>Émettre l’avoir</SubmitButton></form></details>}
  </>;
}
function D({ t, v }: { t: string; v: string }) { return <div><dt>{t}</dt><dd>{v}</dd></div>; }
function formatCentsInput(cents: number) { return `${Math.floor(cents / 100)},${String(cents % 100).padStart(2, "0")}`; }
