import Link from "next/link";
import { notFound } from "next/navigation";
import { ConfirmSubmitButton } from "@/components/sales/confirm-submit-button";
import { PaymentForm } from "@/components/sales/payment-form";
import { RefundForm } from "@/components/sales/refund-form";
import { CancelSaleForm } from "@/components/sales/cancel-sale-form";
import { SaleStatusBadge } from "@/components/sales/status-badge";
import { getAuthenticatedContext } from "@/lib/auth/context";
import { calculateSaleFinancials, formatEuroCents } from "@/lib/sales/calculations";
import { deleteSaleDraftAction, validateSaleAction } from "@/lib/sales/actions";
import { paymentMethodLabels, refundKindLabels, saleChannelLabels } from "@/lib/sales/labels";
import { getSale } from "@/lib/sales/queries";
import { formatFrenchDate } from "@/lib/utils/format";

const successMessages: Record<string, string> = { "brouillon-cree": "Le brouillon a été créé.", "brouillon-modifie": "Le brouillon a été modifié.", "vente-validee": "La vente est maintenant validée et ses montants sont figés.", "encaissement-ajoute": "L’encaissement définitif a été enregistré.", "remboursement-ajoute": "Le remboursement définitif a été enregistré.", "vente-annulee": "La vente a été annulée." };

export default async function SaleDetailPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const { id } = await params; const query = await searchParams; const { context } = await getAuthenticatedContext(); if (!context.business) return null;
  const sale = await getSale(context.business.id, id); if (!sale) notFound(); const financials = calculateSaleFinancials(sale);
  const message = typeof query.message === "string" ? successMessages[query.message] : undefined; const error = typeof query.erreur === "string" ? query.erreur : undefined;
  return <><Link className="back-link" href="/ventes">← Toutes les ventes</Link><header className="page-header sale-detail-header"><div><p className="eyebrow">Vente</p><h1>{sale.reference}</h1><p>{formatFrenchDate(sale.ordered_on)} · {saleChannelLabels[sale.channel]}</p></div><SaleStatusBadge status={sale.status} /></header>{message && <p className="form-message success" role="status">{message}</p>}{error && <p className="form-message" role="alert">{error}</p>}
    {sale.status === "draft" && <section className="sale-actions"><Link className="secondary-link" href={`/ventes/${sale.id}/modifier`}>Modifier</Link><form action={validateSaleAction}><input type="hidden" name="saleId" value={sale.id} /><ConfirmSubmitButton message="La validation fige définitivement les montants, lignes, date et canal. Confirmer ?">Valider définitivement</ConfirmSubmitButton></form><form action={deleteSaleDraftAction}><input type="hidden" name="saleId" value={sale.id} /><ConfirmSubmitButton danger message="Supprimer définitivement ce brouillon ?">Supprimer le brouillon</ConfirmSubmitButton></form></section>}
    <section className="sale-detail-grid"><article className="card"><h2>Commande</h2><dl className="detail-list"><div><dt>Cliente</dt><dd>{sale.customer_name ?? "Non renseignée"}</dd></div><div><dt>Canal</dt><dd>{saleChannelLabels[sale.channel]}</dd></div><div><dt>Notes</dt><dd>{sale.notes ?? "Aucune"}</dd></div></dl></article><article className="card"><h2>Résumé financier</h2><dl className="detail-list"><div><dt>Total de la vente</dt><dd>{formatEuroCents(financials.totalCents)}</dd></div><div><dt>Encaissé brut</dt><dd>{formatEuroCents(financials.grossPaidCents)}</dd></div><div><dt>Commissions</dt><dd>{formatEuroCents(financials.platformFeesCents)}</dd></div><div><dt>Net versé</dt><dd>{formatEuroCents(financials.netDepositedCents)}</dd></div><div><dt>Remboursé</dt><dd>{formatEuroCents(financials.refundedCents)}</dd></div><div><dt>Encaissement net</dt><dd>{formatEuroCents(financials.netCollectedCents)}</dd></div><div className="detail-total"><dt>Reste à encaisser</dt><dd>{formatEuroCents(financials.remainingCents)}</dd></div></dl></article></section>
    <section className="card sale-items-detail"><h2>Lignes de vente</h2>{sale.sale_items.map((item) => <div className="item-detail" key={item.id}><div><strong>{item.description}</strong><span>{item.quantity} × {formatEuroCents(item.unit_price_cents)}</span></div><strong>{formatEuroCents(item.line_total_cents)}</strong></div>)}<dl className="detail-list totals-list"><div><dt>Sous-total</dt><dd>{formatEuroCents(sale.subtotal_cents)}</dd></div><div><dt>Livraison</dt><dd>{formatEuroCents(sale.shipping_cents)}</dd></div><div><dt>Remise</dt><dd>− {formatEuroCents(sale.discount_cents)}</dd></div></dl></section>
    <section className="history-section"><div className="section-heading"><div><p className="eyebrow">Paiements</p><h2>Encaissements et remboursements</h2></div>{sale.status === "validated" && financials.remainingCents > 0 && <details className="action-panel"><summary className="button">Ajouter un encaissement</summary><PaymentForm saleId={sale.id} remainingCents={financials.remainingCents} /></details>}</div>
      {sale.payments.length === 0 ? <p className="history-empty">Aucun encaissement enregistré.</p> : sale.payments.map((payment) => { const refunded = payment.refunds.reduce((sum, refund) => sum + refund.amount_cents, 0); return <article className="payment-card" key={payment.id}><header><div><strong>{formatEuroCents(payment.gross_amount_cents)} brut</strong><span>{formatFrenchDate(payment.received_on)} · {paymentMethodLabels[payment.method]}</span></div><div className="payment-net"><span>Commission {formatEuroCents(payment.platform_fee_cents)}</span><strong>Net versé {formatEuroCents(payment.net_deposit_cents)}</strong></div></header>{payment.refunds.map((refund) => <div className="refund-row" key={refund.id}><span>{refundKindLabels[refund.kind]} · {formatFrenchDate(refund.refunded_on)}</span><strong>− {formatEuroCents(refund.amount_cents)}</strong><small>{refund.reason}</small></div>)}{refunded < payment.gross_amount_cents && <details className="action-panel refund-panel"><summary className="secondary-link">Ajouter un remboursement</summary><RefundForm saleId={sale.id} payment={payment} /></details>}</article>; })}
    </section>{sale.status === "validated" && financials.netCollectedCents === 0 && <details className="action-panel cancellation-panel"><summary className="secondary-link danger-text">Annuler la vente</summary><CancelSaleForm saleId={sale.id} /></details>}
  </>;
}
