import{readFileSync,readdirSync}from"node:fs";import{join}from"node:path";import{describe,expect,it}from"vitest";import{MATERIAL_UNIT_IMMUTABLE_MESSAGE}from"./errors";
const migration=readFileSync(join(process.cwd(),"supabase/migrations/20260806210000_products_costing.sql"),"utf8").replace(/\s+/g," ");const actions=readFileSync(join(process.cwd(),"src/lib/products/actions.ts"),"utf8");
const revokeStart=migration.indexOf("revoke all on function");const grantStart=migration.indexOf("grant execute on function",revokeStart);const revoke=migration.slice(revokeStart,migration.indexOf("from public;",revokeStart)+"from public;".length);const grant=migration.slice(grantStart,migration.indexOf("to authenticated;",grantStart)+"to authenticated;".length);
const saveSql=migration.slice(migration.indexOf("create function public.save_product_with_recipe"),migration.indexOf("create function public.get_product_costing"));const saveAction=actions.slice(actions.indexOf("export async function saveProductAction"),actions.indexOf("export async function archiveProductAction"));
describe("enregistrement atomique produit et recette",()=>{
 it("effectue une seule mutation RPC depuis la Server Action",()=>{expect(saveAction.match(/\.rpc\(/g)).toHaveLength(1);expect(saveAction).toContain('.rpc("save_product_with_recipe"');expect(saveAction).not.toContain('"create_product"');expect(saveAction).not.toContain('"update_product"');expect(saveAction).not.toContain('"replace_product_recipe"')});
 it("transmet produit et recette à la même RPC",()=>{expect(saveAction).toContain("p_product_id:p.productId??null");expect(saveAction).toContain("p_lines:recipe");expect(saveSql).toContain("insert into public.products");expect(saveSql).toContain("update public.products");expect(saveSql).toContain("insert into public.product_materials")});
 it("valide toute recette avant de créer ou modifier un produit",()=>{const validation=saveSql.indexOf("perform public.validate_product_recipe");expect(validation).toBeGreaterThan(0);expect(saveSql.indexOf("insert into public.products")).toBeGreaterThan(validation);expect(saveSql.indexOf("update public.products")).toBeGreaterThan(validation);expect(saveSql.indexOf("delete from public.product_materials")).toBeGreaterThan(validation)});
 it("empêche donc une recette invalide de laisser une création ou modification",()=>{expect(saveSql).toContain("Cette validation complète précède strictement toute écriture");expect(saveSql.indexOf("cross-business material denied")).toBe(-1);expect(migration.indexOf("cross-business material denied")).toBeLessThan(migration.indexOf("create function public.save_product_with_recipe"))});
 it("révoque la RPC atomique à public et l'accorde à authenticated",()=>{const signature="public.save_product_with_recipe(uuid,uuid,text,text,public.product_category,bigint,integer,bigint,integer,text,boolean,jsonb)";expect(revoke).toContain("public.validate_product_recipe(uuid,jsonb)");expect(revoke).toContain(signature);expect(revoke).toContain("from public;");expect(grant).toContain(signature);expect(grant).toContain("to authenticated;")});
 it("interdit les anciennes mutations produit aux rôles applicatifs",()=>{const create="public.create_product(uuid,text,text,public.product_category,bigint,integer,bigint,integer,text)";const update="public.update_product(uuid,uuid,text,text,public.product_category,bigint,integer,bigint,integer,text,boolean)";expect(revoke).toContain(create);expect(revoke).toContain(update);expect(grant).not.toContain(create);expect(grant).not.toContain(update)});
 it("conserve le remplacement indépendant de recette pour authenticated",()=>{expect(grant).toContain("public.replace_product_recipe(uuid,uuid,jsonb)")});
});
describe("unité des matières utilisées",()=>{
 it("autorise le changement d'unité tant qu'aucune recette ne référence la matière",()=>{expect(migration).toContain("current_unit<>p_unit and exists(select 1 from public.product_materials")});
 it("refuse le changement d'unité après utilisation",()=>{expect(migration).toContain("raise exception 'material unit is immutable once used'")});
 it("autorise toujours la modification du coût du lot",()=>{const guard=migration.indexOf("material unit is immutable once used");const update=migration.indexOf("update public.materials set name=",guard);expect(update).toBeGreaterThan(guard);expect(migration.slice(update,update+500)).toContain("package_cost_cents=p_package_cost_cents")});
 it("expose le message français exact",()=>expect(MATERIAL_UNIT_IMMUTABLE_MESSAGE).toBe("L’unité d’une matière déjà utilisée ne peut plus être modifiée. Créez une nouvelle matière pour utiliser une autre unité."));
 it("ne crée aucune migration supplémentaire",()=>{const files=readdirSync(join(process.cwd(),"supabase/migrations")).filter(name=>name.includes("products_costing"));expect(files).toEqual(["20260806210000_products_costing.sql"])});
});
