import type{CostingSettings,ProductCosting}from"@/types/products";
export interface MaterialConsumption{packageCostCents:number;packageQuantityMilliunits:number;quantityMilliunits:number}
const zero=BigInt(0),one=BigInt(1),two=BigInt(2);
function exact(value:number,label:string){if(!Number.isSafeInteger(value))throw new Error(`${label} hors de la plage sûre`);return BigInt(value)}
function gcd(a:bigint,b:bigint){a=a<zero?-a:a;b=b<zero?-b:b;while(b!==zero){const r=a%b;a=b;b=r}return a||one}
function add(a:{n:bigint;d:bigint},b:{n:bigint;d:bigint}){const common=gcd(a.d,b.d);const n=a.n*(b.d/common)+b.n*(a.d/common);const d=(a.d/common)*b.d;const reduction=gcd(n,d);return{n:n/reduction,d:d/reduction}}
function roundRatio(n:bigint,d:bigint){if(n<zero||d<=zero)throw new Error("Rapport invalide");return(n+d/two)/d}
function safe(value:bigint,label:string){const n=Number(value);if(!Number.isSafeInteger(n))throw new Error(`${label} trop élevé`);return n}
export function calculateRawMaterialsCents(lines:MaterialConsumption[]){let total={n:zero,d:one};for(const line of lines){const cost=exact(line.packageCostCents,"Coût du lot"),quantity=exact(line.quantityMilliunits,"Quantité consommée"),pack=exact(line.packageQuantityMilliunits,"Quantité du lot");if(cost<=zero||quantity<=zero||pack<=zero)throw new Error("Matière invalide");total=add(total,{n:cost*quantity,d:pack});}return safe(roundRatio(total.n,total.d),"Total matières")}
export function calculateProductCost(input:{materials:MaterialConsumption[];materialLossBasisPoints:number;laborMinutes:number;packagingCostCents:number|null;salePriceCents:number;settings:CostingSettings}):ProductCosting{const raw=calculateRawMaterialsCents(input.materials);const loss=safe(roundRatio(exact(raw,"Matières")*exact(input.materialLossBasisPoints,"Pertes"),BigInt(10000)),"Pertes");const labor=safe(roundRatio(exact(input.laborMinutes,"Minutes")*exact(input.settings.labor_hourly_rate_cents,"Taux horaire"),BigInt(60)),"Main-d’œuvre");const packaging=input.packagingCostCents??input.settings.default_packaging_cost_cents;const manufacturing=safe(exact(raw,"Matières")+exact(loss,"Pertes")+exact(labor,"Main-d’œuvre")+exact(packaging,"Emballage"),"Coût de fabrication");const margin=safe(exact(input.salePriceCents,"Prix de vente")-exact(manufacturing,"Coût de fabrication"),"Marge");return{rawMaterialsCents:raw,materialLossCents:loss,laborCents:labor,packagingCents:packaging,manufacturingCostCents:manufacturing,grossMarginCents:margin,marginRatePercent:input.salePriceCents>0?margin/input.salePriceCents*100:null}}
export function formatMilliunits(value:number){return(value/1000).toLocaleString("fr-FR",{maximumFractionDigits:3})}
export function formatIndicativeUnitCost(cost:number,quantity:number){return(cost*1000/quantity/100).toLocaleString("fr-FR",{minimumFractionDigits:2,maximumFractionDigits:6})}
