import{readFileSync}from"node:fs";import{join}from"node:path";import{describe,expect,it}from"vitest";
const migration=readFileSync(join(process.cwd(),"supabase/migrations/20260806210000_products_costing.sql"),"utf8");const sql=migration.replace(/\s+/g," ");
describe("migration produits et coûts",()=>{
 it("crée les enums et quatre tables attendues",()=>{expect(sql).toContain("material_unit as enum ('piece','gram','centimeter','milliliter')");expect(sql).toContain("product_category as enum ('necklace','bracelet','earrings','ring','accessory','other')");expect(migration.match(/^create table public\./gm)).toHaveLength(4)});
 it("active RLS partout sans politique directe d'écriture",()=>{expect(migration.match(/enable row level security/g)).toHaveLength(4);expect(migration).not.toMatch(/create policy .* for (insert|update|delete|all)/i);expect(sql).toContain("revoke insert,update,delete on table public.materials")});
 it("définit les RPC et révoque leurs droits publics avant les grants ciblés",()=>{for(const name of["create_material","update_material","archive_material","create_product","update_product","archive_product","replace_product_recipe","save_product_with_recipe","update_costing_settings","get_costing_settings","get_product_costing"])expect(sql).toContain(`public.${name}(`);expect(sql).toContain("from public; grant execute");expect(sql).toContain("to authenticated")});
 it("utilise numeric et un arrondi unique après la somme rationnelle",()=>{expect(sql).toContain("sum((m.package_cost_cents::numeric*pm.quantity_milliunits::numeric)/nullif(m.package_quantity_milliunits::numeric,0))");expect(sql).toContain("raw_rounded:=round(raw_exact)");expect(sql).not.toContain("sum(round(")});
 it("valide toute la recette avant son remplacement atomique",()=>{const validation=sql.indexOf("cross-business material denied");const deletion=sql.indexOf("delete from public.product_materials");expect(validation).toBeGreaterThan(0);expect(deletion).toBeGreaterThan(validation);expect(sql).toContain("duplicate recipe line")});
 it("n'ajoute ni Storage ni service_role",()=>{expect(migration).not.toContain("storage.");expect(migration).not.toContain("service_role")});
});
