import"server-only";import{createClient}from"@/lib/supabase/server";import{loadAllExpensePages}from"@/lib/expenses/pagination";import type{CostingSettings,Material,Product,ProductCategory,ProductCosting,ProductListItem}from"@/types/products";
const productSelect="id,business_id,name,sku,category,sale_price_cents,labor_minutes,packaging_cost_cents,material_loss_basis_points,notes,is_active,product_materials(id,material_id,quantity_milliunits,position,materials(id,business_id,name,internal_reference,supplier_id,unit,package_quantity_milliunits,package_cost_cents,notes,is_active,suppliers(name)))";
function fail(label:string,code?:string):never{console.error(label,{code});throw new Error("PRODUCT_DATA_LOAD_FAILED")}
function safeAmount(value:unknown){const amount=Number(value);if(!Number.isSafeInteger(amount))fail("Montant produit hors plage sûre","UNSAFE_INTEGER");return amount}
function normalizeProduct(value:unknown):Product{const p=value as Product;return{...p,product_materials:(p.product_materials??[]).sort((a,b)=>a.position-b.position)}}
async function costing(s:Awaited<ReturnType<typeof createClient>>,businessId:string,product:Product):Promise<ProductCosting>{if(!s)throw new Error("PRODUCT_DATA_LOAD_FAILED");const{data,error}=await s.rpc("get_product_costing",{p_product_id:product.id,p_business_id:businessId});if(error)fail("Calcul du coût produit impossible",error.code);const row=(Array.isArray(data)?data[0]:data)as Record<string,unknown>|null;if(!row)fail("Calcul du coût produit absent","NO_DATA");const manufacturing=safeAmount(row.manufacturing_cost_cents);const margin=safeAmount(row.gross_margin_cents);return{rawMaterialsCents:safeAmount(row.raw_materials_cents),materialLossCents:safeAmount(row.material_loss_cents),laborCents:safeAmount(row.labor_cents),packagingCents:safeAmount(row.packaging_cents),manufacturingCostCents:manufacturing,grossMarginCents:margin,marginRatePercent:product.sale_price_cents>0?margin/product.sale_price_cents*100:null}}
export async function listMaterials(businessId:string):Promise<Material[]>{const s=await createClient();if(!s)throw new Error("PRODUCT_DATA_LOAD_FAILED");return loadAllExpensePages(async(from,to)=>{const{data,error}=await s.from("materials").select("id,business_id,name,internal_reference,supplier_id,unit,package_quantity_milliunits,package_cost_cents,notes,is_active,suppliers(name)").eq("business_id",businessId).order("is_active",{ascending:false}).order("name").range(from,to);return{data:(data??[])as unknown as Material[],error};},"PRODUCT_DATA_LOAD_FAILED",code=>console.error("Lecture des matières impossible",{code}));}
export async function listProducts(businessId:string,filters:{search?:string;category?:ProductCategory;active?:"active"|"archived"}={}):Promise<ProductListItem[]>{const s=await createClient();if(!s)throw new Error("PRODUCT_DATA_LOAD_FAILED");const rows=await loadAllExpensePages(async(from,to)=>{let q=s.from("products").select(productSelect).eq("business_id",businessId).order("is_active",{ascending:false}).order("name").range(from,to);if(filters.category)q=q.eq("category",filters.category);if(filters.active)q=q.eq("is_active",filters.active==="active");const{data,error}=await q;return{data:(data??[]).map(normalizeProduct),error};},"PRODUCT_DATA_LOAD_FAILED",code=>console.error("Lecture des produits impossible",{code}));const search=filters.search?.trim().toLowerCase().slice(0,80);const visible=rows.filter(p=>!search||`${p.name} ${p.sku??""}`.toLowerCase().includes(search)).slice(0,100);return Promise.all(visible.map(async p=>({...p,costing:await costing(s,businessId,p)})));}
export async function getProduct(businessId:string,id:string):Promise<ProductListItem|null>{const s=await createClient();if(!s)throw new Error("PRODUCT_DATA_LOAD_FAILED");const{data,error}=await s.from("products").select(productSelect).eq("business_id",businessId).eq("id",id).maybeSingle();if(error)fail("Lecture du produit impossible",error.code);if(!data)return null;const product=normalizeProduct(data);return{...product,costing:await costing(s,businessId,product)}}
export async function getCostingSettings(businessId:string):Promise<CostingSettings>{const s=await createClient();if(!s)throw new Error("PRODUCT_DATA_LOAD_FAILED");const{data,error}=await s.rpc("get_costing_settings",{p_business_id:businessId});if(error)fail("Lecture des paramètres de coût impossible",error.code);const row=(Array.isArray(data)?data[0]:data)as Record<string,number>|null;return{labor_hourly_rate_cents:Number(row?.labor_hourly_rate_cents??0),default_packaging_cost_cents:Number(row?.default_packaging_cost_cents??0)}}
