import{z}from"zod";import{parseFrenchMoneyToCents}from"../sales/calculations";
const optional=(max:number)=>z.preprocess(v=>String(v??"").trim(),z.string().max(max));
const money=(allowZero=true)=>z.preprocess(v=>{try{return parseFrenchMoneyToCents(String(v));}catch{return Number.NaN;}},allowZero?z.number().int().min(0).max(9000000000000):z.number().int().positive().max(9000000000000));
export function parseQuantityToMilliunits(value:string){const normalized=value.trim().replace(",",".");if(!/^\d+(?:\.\d{1,3})?$/.test(normalized))throw new Error("Quantité invalide");const[whole,dec=""]=normalized.split(".");const result=BigInt(whole)*BigInt(1000)+BigInt(dec.padEnd(3,"0"));const number=Number(result);if(result<=BigInt(0)||!Number.isSafeInteger(number)||number>9000000000000000)throw new Error("Quantité invalide");return number}
const quantity=z.preprocess(v=>{try{return parseQuantityToMilliunits(String(v));}catch{return Number.NaN;}},z.number().int().positive().safe());
export const materialSchema=z.object({materialId:z.string().uuid().optional(),name:z.string().trim().min(1).max(160),internalReference:optional(80),supplierId:z.string().uuid().or(z.literal("")),unit:z.enum(["piece","gram","centimeter","milliliter"]),packageQuantity:quantity,packageCost:money(false),notes:optional(2000),isActive:z.boolean().default(true)});
export const productSchema=z.object({productId:z.string().uuid().optional(),name:z.string().trim().min(1).max(160),sku:optional(80),category:z.enum(["necklace","bracelet","earrings","ring","accessory","other"]),salePrice:money(),laborMinutes:z.coerce.number().int().min(0).max(10080),packagingCost:z.union([money(),z.literal("")]),materialLossPercent:z.coerce.number().min(0).max(100).transform(v=>Math.round(v*100)),notes:optional(2000),isActive:z.boolean().default(true)});
export const costingSettingsSchema=z.object({laborHourlyRate:money(),defaultPackagingCost:money()});
export interface ProductActionState{error?:string;fieldErrors?:Record<string,string[]|undefined>}
