import "server-only";
import { createClient } from "@/lib/supabase/server";
import type { DocumentKind, Expense, ExpenseCategory, ExpenseStatus, RecurringExpenseTemplate, Supplier } from "@/types/expenses";
import { calculateExpenseTotals, getParisMonthBounds, type ExpenseTotalsSource } from "./calculations";
import { loadAllExpensePages, sumExpenseAmounts } from "./pagination";

const expenseSelect=`id,business_id,reference,purchased_on,due_on,supplier_id,category,subcategory,nature,cost_behavior,description,external_reference,total_amount_cents,professional_share_basis_points,business_amount_cents,notes,status,validated_at,cancelled_at,cancellation_reason,suppliers(id,name),expense_payments(id,paid_on,bank_debited_on,amount_cents,business_amount_cents,method,external_reference,notes,expense_refunds(id,expense_payment_id,received_on,amount_cents,business_amount_cents,kind,reason,external_reference)),expense_documents(id,document_id,documents(id,kind,storage_path,original_name,mime_type,size_bytes,created_at))`;
function normalizeExpense(v:unknown):Expense{const e=v as Expense;return{...e,expense_payments:(e.expense_payments??[]).map(p=>({...p,expense_refunds:p.expense_refunds??[]})),expense_documents:e.expense_documents??[]};}
export interface ExpenseFilters{status?:ExpenseStatus;category?:ExpenseCategory;supplierId?:string;from?:string;to?:string;search?:string;documents?:"with"|"without";}
export async function listExpenses(businessId:string,filters:ExpenseFilters={}):Promise<Expense[]>{const s=await createClient();if(!s)return[];const rows:Expense[]=[];for(let from=0;;from+=1000){let q=s.from("expenses").select(expenseSelect).eq("business_id",businessId).order("purchased_on",{ascending:false}).order("id",{ascending:true}).range(from,from+999);if(filters.status)q=q.eq("status",filters.status);if(filters.category)q=q.eq("category",filters.category);if(filters.supplierId)q=q.eq("supplier_id",filters.supplierId);if(filters.from)q=q.gte("purchased_on",filters.from);if(filters.to)q=q.lte("purchased_on",filters.to);const{data,error}=await q;if(error){console.error("Lecture des dépenses impossible",{code:error.code});return[];}const page=(data??[]).map(normalizeExpense);rows.push(...page);if(page.length<1000)break;}let filtered=rows;if(filters.search){const x=filters.search.toLowerCase().slice(0,80);filtered=filtered.filter(e=>`${e.reference} ${e.description} ${e.external_reference??""} ${e.suppliers?.name??""}`.toLowerCase().includes(x));}if(filters.documents)filtered=filtered.filter(e=>(e.expense_documents.length>0)===(filters.documents==="with"));return filtered.slice(0,100);}
export async function getExpense(businessId:string,id:string):Promise<Expense|null>{const s=await createClient();if(!s)return null;const{data,error}=await s.from("expenses").select(expenseSelect).eq("business_id",businessId).eq("id",id).maybeSingle();if(error)console.error("Lecture de la dépense impossible",{code:error.code});return data?normalizeExpense(data):null;}
async function getGlobalExpenseTotals(businessId:string){const s=await createClient();if(!s)return calculateExpenseTotals([]);const rows:ExpenseTotalsSource[]=[];for(let from=0;;from+=1000){const{data,error}=await s.from("expenses").select("status,total_amount_cents,business_amount_cents,expense_payments(amount_cents,business_amount_cents,expense_refunds(amount_cents,business_amount_cents)),expense_documents(count)").eq("business_id",businessId).order("id").range(from,from+999);if(error){console.error("Agrégation des dépenses impossible",{code:error.code});throw new Error("EXPENSE_AGGREGATION_FAILED");}const page=(data??[]).map(v=>{const x=v as unknown as ExpenseTotalsSource&{expense_documents?:Array<{count:number}>};return{...x,document_count:x.expense_documents?.[0]?.count??0};});rows.push(...page);if(page.length<1000)break;}return calculateExpenseTotals(rows);}
export async function getExpensesOverview(businessId:string){const[expenses,totals]=await Promise.all([listExpenses(businessId),getGlobalExpenseTotals(businessId)]);return{expenses,totals};}
export async function listSuppliers(businessId:string):Promise<Supplier[]>{const s=await createClient();if(!s)return[];const{data,error}=await s.from("suppliers").select("id,business_id,name,email,phone,website,address_line_1,address_line_2,postal_code,city,country_code,registration_number,notes,is_active").eq("business_id",businessId).order("is_active",{ascending:false}).order("name");if(error){console.error("Lecture des fournisseurs impossible",{code:error.code});return[];}return(data??[]) as Supplier[];}
export async function getSupplierStats(businessId:string){const[s,suppliers]=await Promise.all([createClient(),listSuppliers(businessId)]);if(!s)throw new Error("EXPENSE_SUPPLIER_AGGREGATION_FAILED");const expenses=await loadAllExpensePages(async(from,to)=>{const{data,error}=await s.from("expenses").select("supplier_id,business_amount_cents,purchased_on").eq("business_id",businessId).eq("status","validated").order("id").range(from,to);return{data,error};},"EXPENSE_SUPPLIER_AGGREGATION_FAILED",code=>console.error("Agrégation fournisseurs impossible",{code}));return suppliers.map(supplier=>{const rows=expenses.filter(e=>e.supplier_id===supplier.id);return{...supplier,expenseCount:rows.length,validatedCents:sumExpenseAmounts(rows,e=>e.business_amount_cents),lastExpense:rows.reduce<string|null>((last,e)=>!last||e.purchased_on>last?e.purchased_on:last,null)};});}
export async function listRecurringTemplates(businessId:string):Promise<RecurringExpenseTemplate[]>{const s=await createClient();if(!s)return[];const{data,error}=await s.from("recurring_expense_templates").select("id,business_id,supplier_id,category,subcategory,nature,cost_behavior,description,estimated_amount_cents,professional_share_basis_points,frequency,next_due_on,last_generated_on,notes,is_active,suppliers(id,name)").eq("business_id",businessId).order("next_due_on");if(error){console.error("Lecture des récurrences impossible",{code:error.code});return[];}return(data??[]) as unknown as RecurringExpenseTemplate[];}
export interface ListedDocument{documentId:string;expenseId:string;expenseReference:string;supplierName:string|null;category:ExpenseCategory;kind:DocumentKind;originalName:string;mimeType:string;sizeBytes:number;createdAt:string;signedUrl:string|null;}
export async function listExpenseDocuments(businessId:string):Promise<{documents:ListedDocument[];missing:Array<{id:string;reference:string;description:string}>}>{const s=await createClient();if(!s)return{documents:[],missing:[]};const links:unknown[]=[];for(let from=0;;from+=1000){const{data,error}=await s.from("expense_documents").select("expense_id,documents(id,kind,storage_path,original_name,mime_type,size_bytes,created_at),expenses(reference,description,status,category,suppliers(name))").eq("business_id",businessId).order("created_at",{ascending:false}).order("id").range(from,from+999);if(error){console.error("Lecture des justificatifs impossible",{code:error.code});return{documents:[],missing:[]};}links.push(...(data??[]));if((data??[]).length<1000)break;}const documents:ListedDocument[]=[];for(const value of links){const row=value as {expense_id:string;documents:unknown;expenses:unknown};const d=row.documents as {id:string;kind:DocumentKind;storage_path:string;original_name:string;mime_type:string;size_bytes:number;created_at:string}|null;const e=row.expenses as {reference:string;category:ExpenseCategory;suppliers:{name:string}|null}|null;if(!d||!e)continue;const{data:url}=await s.storage.from("expense-documents").createSignedUrl(d.storage_path,60);documents.push({documentId:d.id,expenseId:row.expense_id,expenseReference:e.reference,supplierName:e.suppliers?.name??null,category:e.category,kind:d.kind,originalName:d.original_name,mimeType:d.mime_type,sizeBytes:d.size_bytes,createdAt:d.created_at,signedUrl:url?.signedUrl??null});}const missing:Array<{id:string;reference:string;description:string}>=[];for(let from=0;;from+=1000){const{data,error}=await s.from("expenses").select("id,reference,description,expense_documents(count)").eq("business_id",businessId).eq("status","validated").order("id").range(from,from+999);if(error){console.error("Lecture des justificatifs manquants impossible",{code:error.code});break;}for(const x of data??[])if(((x.expense_documents as unknown as Array<{count:number}>)?.[0]?.count??0)===0)missing.push({id:x.id,reference:x.reference,description:x.description});if((data??[]).length<1000)break;}return{documents,missing};}
export async function getDashboardExpenses(businessId:string){const s=await createClient();if(!s)throw new Error("EXPENSE_DASHBOARD_AGGREGATION_FAILED");const b=getParisMonthBounds();const payments=await loadAllExpensePages(async(from,to)=>{const{data,error}=await s.from("expense_payments").select("business_amount_cents").eq("business_id",businessId).gte("paid_on",b.start).lt("paid_on",b.end).order("id").range(from,to);return{data,error};},"EXPENSE_DASHBOARD_AGGREGATION_FAILED",code=>console.error("Paiements mensuels indisponibles",{code}));const refunds=await loadAllExpensePages(async(from,to)=>{const{data,error}=await s.from("expense_refunds").select("business_amount_cents").eq("business_id",businessId).gte("received_on",b.start).lt("received_on",b.end).order("id").range(from,to);return{data,error};},"EXPENSE_DASHBOARD_AGGREGATION_FAILED",code=>console.error("Remboursements mensuels indisponibles",{code}));const paid=sumExpenseAmounts(payments,x=>x.business_amount_cents);const refunded=sumExpenseAmounts(refunds,x=>x.business_amount_cents);const totals=await getGlobalExpenseTotals(businessId);return{monthlyNetCents:paid-refunded,missingDocuments:totals.missingDocuments};}
