import { z } from "zod";
import { parseFrenchMoneyToCents } from "../sales/calculations";
import { EXPENSE_DOCUMENT_SIZE_ERROR, getExpenseDocumentSizeError } from "./document-limits";
const date=/^\d{4}-\d{2}-\d{2}$/; const optional=(max:number)=>z.preprocess(v=>String(v??"").trim(),z.string().max(max));
const money=z.preprocess(v=>{try{return parseFrenchMoneyToCents(String(v));}catch{return Number.NaN;}},z.number().int().positive().safe());
export const expenseCategories=["raw_materials","packaging","shipping","marketplace_fees","software","marketing","market_fees","equipment","insurance","bank_fees","telecommunications","professional_services","taxes_social","travel","office","training","other"] as const;
export const expenseFormSchema=z.object({expenseId:z.string().uuid().optional(),purchasedOn:z.string().regex(date),dueOn:z.string().regex(date).or(z.literal("")),supplierId:z.string().uuid().or(z.literal("")),category:z.enum(expenseCategories),subcategory:optional(120),nature:z.enum(["operating","investment","tax_social"]),costBehavior:z.enum(["fixed","variable","exceptional"]),description:z.string().trim().min(1).max(500),externalReference:optional(200),totalAmount:money,professionalShare:z.coerce.number().min(0).max(100).transform(v=>Math.round(v*100)),notes:optional(2000)}).refine(v=>!v.dueOn||v.dueOn>=v.purchasedOn,{message:"L’échéance doit suivre la date d’achat.",path:["dueOn"]});
export const expensePaymentSchema=z.object({expenseId:z.string().uuid(),paidOn:z.string().regex(date),bankDebitedOn:z.string().regex(date).or(z.literal("")),amount:money,method:z.enum(["cash","card","bank_transfer","paypal","cheque","direct_debit","other"]),externalReference:optional(200),notes:optional(2000)}).refine(v=>!v.bankDebitedOn||v.bankDebitedOn>=v.paidOn,{message:"La date bancaire doit suivre le paiement.",path:["bankDebitedOn"]});
export const expenseRefundSchema=z.object({expenseId:z.string().uuid(),paymentId:z.string().uuid(),paidOn:z.string().regex(date),receivedOn:z.string().regex(date),amount:money,kind:z.enum(["supplier_refund","credit_note","correction"]),reason:z.string().trim().min(2).max(500),externalReference:optional(200)}).refine(v=>v.receivedOn>=v.paidOn,{message:"Le remboursement doit suivre le paiement.",path:["receivedOn"]});
export const cancellationSchema=z.object({expenseId:z.string().uuid(),reason:z.string().trim().min(2).max(500)});
export const supplierSchema=z.object({supplierId:z.string().uuid().optional(),name:z.string().trim().min(1).max(160),email:optional(254),phone:optional(40),website:optional(300),addressLine1:optional(200),addressLine2:optional(200),postalCode:optional(20),city:optional(120),countryCode:z.preprocess(v=>String(v??"FR").trim().toUpperCase(),z.string().regex(/^[A-Z]{2}$/)),registrationNumber:optional(80),notes:optional(2000),isActive:z.boolean().default(true)});
export const recurringSchema=z.object({templateId:z.string().uuid().optional(),supplierId:z.string().uuid().or(z.literal("")),category:z.enum(expenseCategories),subcategory:optional(120),nature:z.enum(["operating","investment","tax_social"]),costBehavior:z.enum(["fixed","variable","exceptional"]),description:z.string().trim().min(1).max(500),estimatedAmount:money,professionalShare:z.coerce.number().min(0).max(100).transform(v=>Math.round(v*100)),frequency:z.enum(["monthly","quarterly","yearly"]),nextDueOn:z.string().regex(date),notes:optional(2000),isActive:z.boolean().default(true)});
export const allowedDocumentMimes=["application/pdf","image/jpeg","image/png","image/webp","image/heic","image/heif"] as const;
const extensions:Record<string,string[]>={"application/pdf":["pdf"],"image/jpeg":["jpg","jpeg"],"image/png":["png"],"image/webp":["webp"],"image/heic":["heic"],"image/heif":["heif"]};
export function validateExpenseFile(file:Pick<File,"name"|"size"|"type">):string|null {if(file.size<=0)return EXPENSE_DOCUMENT_SIZE_ERROR;const sizeError=getExpenseDocumentSizeError(file.size);if(sizeError)return sizeError;if(!allowedDocumentMimes.includes(file.type as typeof allowedDocumentMimes[number]))return"Ce type de fichier n’est pas autorisé.";if(file.name.length>255||file.name.includes("..")||/[\\/\0]/.test(file.name))return"Le nom du fichier est dangereux.";const ext=file.name.split(".").pop()?.toLowerCase()??"";if(!extensions[file.type]?.includes(ext))return"L’extension ne correspond pas au type du fichier.";return null;}
export interface ExpenseActionState {error?:string;fieldErrors?:Record<string,string[]|undefined>}
