-- Dépenses, paiements fournisseurs, justificatifs privés et modèles récurrents.
-- Les tables métier sont en lecture seule pour les rôles applicatifs : toutes
-- les mutations passent par les RPC SECURITY DEFININER contrôlées ci-dessous.

create type public.expense_status as enum ('draft', 'validated', 'cancelled');
create type public.expense_category as enum ('raw_materials','packaging','shipping','marketplace_fees','software','marketing','market_fees','equipment','insurance','bank_fees','telecommunications','professional_services','taxes_social','travel','office','training','other');
create type public.expense_nature as enum ('operating','investment','tax_social');
create type public.expense_cost_behavior as enum ('fixed','variable','exceptional');
create type public.expense_payment_method as enum ('cash','card','bank_transfer','paypal','cheque','direct_debit','other');
create type public.expense_refund_kind as enum ('supplier_refund','credit_note','correction');
create type public.document_kind as enum ('supplier_invoice','receipt','bank_proof','credit_note','contract','other');
create type public.recurrence_frequency as enum ('monthly','quarterly','yearly');

create table public.suppliers (
  id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete restrict,
  name text not null, email text, phone text, website text, address_line_1 text, address_line_2 text,
  postal_code text, city text, country_code text not null default 'FR', registration_number text, notes text,
  is_active boolean not null default true, created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  constraint suppliers_id_business_key unique (id,business_id),
  constraint suppliers_name_length check (char_length(btrim(name)) between 1 and 160),
  constraint suppliers_email_length check (email is null or char_length(email) <= 254),
  constraint suppliers_phone_length check (phone is null or char_length(phone) <= 40),
  constraint suppliers_website_length check (website is null or char_length(website) <= 300),
  constraint suppliers_address_lengths check (char_length(coalesce(address_line_1,'')) <= 200 and char_length(coalesce(address_line_2,'')) <= 200 and char_length(coalesce(postal_code,'')) <= 20 and char_length(coalesce(city,'')) <= 120),
  constraint suppliers_country_code check (country_code ~ '^[A-Z]{2}$'),
  constraint suppliers_registration_length check (registration_number is null or char_length(registration_number) <= 80),
  constraint suppliers_notes_length check (notes is null or char_length(notes) <= 2000)
);

create table public.expenses (
  id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete restrict,
  reference text not null, purchased_on date not null, due_on date, supplier_id uuid,
  category public.expense_category not null, subcategory text, nature public.expense_nature not null,
  cost_behavior public.expense_cost_behavior not null, description text not null, external_reference text,
  total_amount_cents bigint not null, professional_share_basis_points integer not null default 10000,
  business_amount_cents bigint generated always as ((total_amount_cents * professional_share_basis_points + 5000) / 10000) stored,
  notes text, status public.expense_status not null default 'draft', created_by uuid references auth.users(id) on delete set null,
  validated_at timestamptz, cancelled_at timestamptz, cancellation_reason text,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  constraint expenses_business_reference_key unique (business_id,reference),
  constraint expenses_id_business_key unique (id,business_id),
  constraint expenses_supplier_business_fk foreign key (supplier_id,business_id) references public.suppliers(id,business_id) on delete restrict,
  constraint expenses_reference_length check (char_length(reference) between 10 and 40),
  constraint expenses_due_date check (due_on is null or due_on >= purchased_on),
  constraint expenses_description_length check (char_length(btrim(description)) between 1 and 500),
  constraint expenses_text_lengths check (char_length(coalesce(subcategory,'')) <= 120 and char_length(coalesce(external_reference,'')) <= 200 and char_length(coalesce(notes,'')) <= 2000),
  constraint expenses_amount_positive check (total_amount_cents between 1 and 9000000000000),
  constraint expenses_share_range check (professional_share_basis_points between 0 and 10000),
  constraint expenses_status_dates check (
    (status='draft' and validated_at is null and cancelled_at is null and cancellation_reason is null) or
    (status='validated' and validated_at is not null and cancelled_at is null and cancellation_reason is null) or
    (status='cancelled' and validated_at is not null and cancelled_at is not null and char_length(btrim(cancellation_reason)) between 2 and 500)
  )
);

create table public.expense_payments (
  id uuid primary key default gen_random_uuid(), business_id uuid not null, expense_id uuid not null,
  paid_on date not null, bank_debited_on date, amount_cents bigint not null, business_amount_cents bigint not null,
  method public.expense_payment_method not null, external_reference text, notes text,
  created_by uuid references auth.users(id) on delete set null, created_at timestamptz not null default now(),
  constraint expense_payments_id_business_expense_key unique (id,business_id,expense_id),
  constraint expense_payments_expense_business_fk foreign key (expense_id,business_id) references public.expenses(id,business_id) on delete restrict,
  constraint expense_payments_amounts check (amount_cents > 0 and business_amount_cents >= 0 and business_amount_cents <= amount_cents),
  constraint expense_payments_bank_date check (bank_debited_on is null or bank_debited_on >= paid_on),
  constraint expense_payments_text_lengths check (char_length(coalesce(external_reference,'')) <= 200 and char_length(coalesce(notes,'')) <= 2000)
);

create table public.expense_refunds (
  id uuid primary key default gen_random_uuid(), business_id uuid not null, expense_id uuid not null, expense_payment_id uuid not null,
  received_on date not null, amount_cents bigint not null, business_amount_cents bigint not null,
  kind public.expense_refund_kind not null, reason text not null, external_reference text,
  created_by uuid references auth.users(id) on delete set null, created_at timestamptz not null default now(),
  constraint expense_refunds_payment_fk foreign key (expense_payment_id,business_id,expense_id) references public.expense_payments(id,business_id,expense_id) on delete restrict,
  constraint expense_refunds_expense_fk foreign key (expense_id,business_id) references public.expenses(id,business_id) on delete restrict,
  constraint expense_refunds_amounts check (amount_cents > 0 and business_amount_cents >= 0 and business_amount_cents <= amount_cents),
  constraint expense_refunds_reason check (char_length(btrim(reason)) between 2 and 500),
  constraint expense_refunds_external_length check (char_length(coalesce(external_reference,'')) <= 200)
);

create table public.documents (
  id uuid primary key, business_id uuid not null references public.businesses(id) on delete restrict,
  kind public.document_kind not null, storage_bucket text not null, storage_path text not null unique,
  original_name text not null, mime_type text not null, size_bytes bigint not null,
  uploaded_by uuid references auth.users(id) on delete set null, created_at timestamptz not null default now(),
  constraint documents_id_business_key unique (id,business_id),
  constraint documents_bucket check (storage_bucket='expense-documents'),
  constraint documents_path_length check (char_length(storage_path) between 10 and 700 and storage_path !~ '(^|/)\.\.(/|$)'),
  constraint documents_name_length check (char_length(btrim(original_name)) between 1 and 255),
  constraint documents_mime check (mime_type in ('application/pdf','image/jpeg','image/png','image/webp','image/heic','image/heif')),
  constraint documents_size check (size_bytes between 1 and 10485760)
);

create table public.expense_documents (
  id uuid primary key default gen_random_uuid(), business_id uuid not null, expense_id uuid not null, document_id uuid not null,
  attached_by uuid references auth.users(id) on delete set null, created_at timestamptz not null default now(),
  constraint expense_documents_unique unique (expense_id,document_id),
  constraint expense_documents_expense_fk foreign key (expense_id,business_id) references public.expenses(id,business_id) on delete restrict,
  constraint expense_documents_document_fk foreign key (document_id,business_id) references public.documents(id,business_id) on delete restrict
);

create table public.recurring_expense_templates (
  id uuid primary key default gen_random_uuid(), business_id uuid not null references public.businesses(id) on delete restrict,
  supplier_id uuid, category public.expense_category not null, subcategory text, nature public.expense_nature not null,
  cost_behavior public.expense_cost_behavior not null, description text not null, estimated_amount_cents bigint not null,
  professional_share_basis_points integer not null default 10000, frequency public.recurrence_frequency not null,
  next_due_on date not null, last_generated_on date, notes text, is_active boolean not null default true,
  created_by uuid references auth.users(id) on delete set null, created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  constraint recurring_templates_id_business_key unique (id,business_id),
  constraint recurring_templates_supplier_fk foreign key (supplier_id,business_id) references public.suppliers(id,business_id) on delete restrict,
  constraint recurring_templates_description check (char_length(btrim(description)) between 1 and 500),
  constraint recurring_templates_amount check (estimated_amount_cents between 1 and 9000000000000),
  constraint recurring_templates_share check (professional_share_basis_points between 0 and 10000),
  constraint recurring_templates_text check (char_length(coalesce(subcategory,'')) <= 120 and char_length(coalesce(notes,'')) <= 2000)
);

create index suppliers_business_active_name_idx on public.suppliers(business_id,is_active,name);
create index expenses_business_purchased_idx on public.expenses(business_id,purchased_on desc);
create index expenses_business_status_purchased_idx on public.expenses(business_id,status,purchased_on desc);
create index expenses_supplier_idx on public.expenses(business_id,supplier_id,purchased_on desc);
create index expenses_category_idx on public.expenses(business_id,category,purchased_on desc);
create index expenses_external_reference_idx on public.expenses(business_id,external_reference) where external_reference is not null;
create index expense_payments_business_paid_idx on public.expense_payments(business_id,paid_on desc);
create index expense_refunds_business_received_idx on public.expense_refunds(business_id,received_on desc);
create index expense_documents_expense_idx on public.expense_documents(business_id,expense_id);
create index recurring_templates_due_idx on public.recurring_expense_templates(business_id,is_active,next_due_on);

create trigger suppliers_set_updated_at before update on public.suppliers for each row execute function public.set_updated_at();
create trigger expenses_set_updated_at before update on public.expenses for each row execute function public.set_updated_at();
create trigger recurring_templates_set_updated_at before update on public.recurring_expense_templates for each row execute function public.set_updated_at();

create function public.protect_expense_mutations() returns trigger language plpgsql set search_path='' as $$
begin
  if tg_op='DELETE' then if old.status<>'draft' then raise exception 'expense is immutable' using errcode='55000'; end if; return old; end if;
  if old.status='cancelled' then raise exception 'expense is immutable' using errcode='55000'; end if;
  if old.status='validated' and (new.status<>'cancelled' or new.business_id<>old.business_id or new.reference<>old.reference or new.purchased_on<>old.purchased_on or new.due_on is distinct from old.due_on or new.supplier_id is distinct from old.supplier_id or new.category<>old.category or new.subcategory is distinct from old.subcategory or new.nature<>old.nature or new.cost_behavior<>old.cost_behavior or new.description<>old.description or new.external_reference is distinct from old.external_reference or new.total_amount_cents<>old.total_amount_cents or new.professional_share_basis_points<>old.professional_share_basis_points or new.notes is distinct from old.notes or new.validated_at<>old.validated_at) then raise exception 'expense is immutable' using errcode='55000'; end if;
  return new;
end $$;
create function public.prevent_expense_financial_mutation() returns trigger language plpgsql set search_path='' as $$ begin raise exception 'financial record is immutable' using errcode='55000'; end $$;
create function public.prevent_document_mutation() returns trigger language plpgsql set search_path='' as $$ begin if tg_op='DELETE' and current_setting('yrelcompta.allow_document_delete',true)='on' then return old; end if; raise exception 'document metadata is immutable' using errcode='55000'; end $$;
create function public.protect_expense_document_delete() returns trigger language plpgsql set search_path='' as $$ declare s public.expense_status; begin if tg_op='UPDATE' then raise exception 'expense document link is immutable' using errcode='55000'; end if; select status into s from public.expenses where id=old.expense_id and business_id=old.business_id; if s is distinct from 'draft' then raise exception 'validated expense document is immutable' using errcode='55000'; end if; return old; end $$;
create trigger expenses_protect before update or delete on public.expenses for each row execute function public.protect_expense_mutations();
create trigger expense_payments_immutable before update or delete on public.expense_payments for each row execute function public.prevent_expense_financial_mutation();
create trigger expense_refunds_immutable before update or delete on public.expense_refunds for each row execute function public.prevent_expense_financial_mutation();
create trigger documents_immutable before update or delete on public.documents for each row execute function public.prevent_document_mutation();
create trigger expense_documents_protect before update or delete on public.expense_documents for each row execute function public.protect_expense_document_delete();

alter table public.suppliers enable row level security;
alter table public.expenses enable row level security;
alter table public.expense_payments enable row level security;
alter table public.expense_refunds enable row level security;
alter table public.documents enable row level security;
alter table public.expense_documents enable row level security;
alter table public.recurring_expense_templates enable row level security;
revoke all on table public.suppliers,public.expenses,public.expense_payments,public.expense_refunds,public.documents,public.expense_documents,public.recurring_expense_templates from anon,authenticated;
grant select on table public.suppliers,public.expenses,public.expense_payments,public.expense_refunds,public.documents,public.expense_documents,public.recurring_expense_templates to authenticated;
create policy suppliers_select_member on public.suppliers for select to authenticated using (public.is_business_member(business_id));
create policy expenses_select_member on public.expenses for select to authenticated using (public.is_business_member(business_id));
create policy expense_payments_select_member on public.expense_payments for select to authenticated using (public.is_business_member(business_id));
create policy expense_refunds_select_member on public.expense_refunds for select to authenticated using (public.is_business_member(business_id));
create policy documents_select_member on public.documents for select to authenticated using (public.is_business_member(business_id));
create policy expense_documents_select_member on public.expense_documents for select to authenticated using (public.is_business_member(business_id));
create policy recurring_templates_select_member on public.recurring_expense_templates for select to authenticated using (public.is_business_member(business_id));

create function public.assert_expense_manager(p_business_id uuid) returns uuid language plpgsql security definer set search_path='' as $$ declare actor uuid:=auth.uid(); begin if actor is null then raise exception 'authentication required' using errcode='42501'; end if; if not public.can_manage_business(p_business_id) then raise exception 'business access denied' using errcode='42501'; end if; return actor; end $$;
revoke all on function public.assert_expense_manager(uuid) from public;

create function public.create_supplier(p_business_id uuid,p_name text,p_email text,p_phone text,p_website text,p_address_line_1 text,p_address_line_2 text,p_postal_code text,p_city text,p_country_code text,p_registration_number text,p_notes text) returns uuid language plpgsql security definer set search_path='' as $$ declare actor uuid:=public.assert_expense_manager(p_business_id); nid uuid:=gen_random_uuid(); begin insert into public.suppliers(id,business_id,name,email,phone,website,address_line_1,address_line_2,postal_code,city,country_code,registration_number,notes,created_by) values(nid,p_business_id,btrim(p_name),nullif(btrim(p_email),''),nullif(btrim(p_phone),''),nullif(btrim(p_website),''),nullif(btrim(p_address_line_1),''),nullif(btrim(p_address_line_2),''),nullif(btrim(p_postal_code),''),nullif(btrim(p_city),''),upper(coalesce(nullif(btrim(p_country_code),''),'FR')),nullif(btrim(p_registration_number),''),nullif(btrim(p_notes),''),actor); insert into public.audit_logs(business_id,user_id,action_type,entity_name,entity_id,new_data) values(p_business_id,actor,'created','supplier',nid,jsonb_build_object('name',btrim(p_name))); return nid; end $$;
create function public.update_supplier(p_supplier_id uuid,p_business_id uuid,p_name text,p_email text,p_phone text,p_website text,p_notes text,p_is_active boolean) returns void language plpgsql security definer set search_path='' as $$ declare actor uuid:=public.assert_expense_manager(p_business_id); begin update public.suppliers set name=btrim(p_name),email=nullif(btrim(p_email),''),phone=nullif(btrim(p_phone),''),website=nullif(btrim(p_website),''),notes=nullif(btrim(p_notes),''),is_active=p_is_active where id=p_supplier_id and business_id=p_business_id; if not found then raise exception 'supplier not found' using errcode='P0002'; end if; insert into public.audit_logs(business_id,user_id,action_type,entity_name,entity_id,new_data) values(p_business_id,actor,'updated','supplier',p_supplier_id,jsonb_build_object('name',btrim(p_name),'is_active',p_is_active)); end $$;
create function public.archive_supplier(p_supplier_id uuid,p_business_id uuid) returns void language plpgsql security definer set search_path='' as $$ declare actor uuid:=public.assert_expense_manager(p_business_id); begin update public.suppliers set is_active=false where id=p_supplier_id and business_id=p_business_id; if not found then raise exception 'supplier not found' using errcode='P0002'; end if; insert into public.audit_logs(business_id,user_id,action_type,entity_name,entity_id,new_data) values(p_business_id,actor,'archived','supplier',p_supplier_id,'{"is_active":false}'); end $$;

create function public.create_expense_draft(p_business_id uuid,p_purchased_on date,p_due_on date,p_supplier_id uuid,p_category public.expense_category,p_subcategory text,p_nature public.expense_nature,p_cost_behavior public.expense_cost_behavior,p_description text,p_external_reference text,p_total_amount_cents bigint,p_professional_share_basis_points integer,p_notes text) returns uuid language plpgsql security definer set search_path='' as $$ declare actor uuid:=public.assert_expense_manager(p_business_id); nid uuid:=gen_random_uuid(); ref text; begin if p_due_on is not null and p_due_on<p_purchased_on then raise exception 'invalid expense dates' using errcode='22023'; end if; ref:='D-'||to_char(p_purchased_on,'YYYYMMDD')||'-'||upper(substr(replace(nid::text,'-',''),1,12)); insert into public.expenses(id,business_id,reference,purchased_on,due_on,supplier_id,category,subcategory,nature,cost_behavior,description,external_reference,total_amount_cents,professional_share_basis_points,notes,created_by) values(nid,p_business_id,ref,p_purchased_on,p_due_on,p_supplier_id,p_category,nullif(btrim(p_subcategory),''),p_nature,p_cost_behavior,btrim(p_description),nullif(btrim(p_external_reference),''),p_total_amount_cents,p_professional_share_basis_points,nullif(btrim(p_notes),''),actor); insert into public.audit_logs(business_id,user_id,action_type,entity_name,entity_id,new_data) values(p_business_id,actor,'created','expense',nid,jsonb_build_object('reference',ref,'total_amount_cents',p_total_amount_cents)); return nid; end $$;
create function public.update_expense_draft(p_expense_id uuid,p_business_id uuid,p_purchased_on date,p_due_on date,p_supplier_id uuid,p_category public.expense_category,p_subcategory text,p_nature public.expense_nature,p_cost_behavior public.expense_cost_behavior,p_description text,p_external_reference text,p_total_amount_cents bigint,p_professional_share_basis_points integer,p_notes text) returns void language plpgsql security definer set search_path='' as $$ declare actor uuid:=public.assert_expense_manager(p_business_id); e public.expenses; begin select * into e from public.expenses where id=p_expense_id and business_id=p_business_id for update; if not found then raise exception 'expense not found' using errcode='P0002'; end if; if e.status<>'draft' then raise exception 'draft required' using errcode='55000'; end if; update public.expenses set purchased_on=p_purchased_on,due_on=p_due_on,supplier_id=p_supplier_id,category=p_category,subcategory=nullif(btrim(p_subcategory),''),nature=p_nature,cost_behavior=p_cost_behavior,description=btrim(p_description),external_reference=nullif(btrim(p_external_reference),''),total_amount_cents=p_total_amount_cents,professional_share_basis_points=p_professional_share_basis_points,notes=nullif(btrim(p_notes),'') where id=p_expense_id; insert into public.audit_logs(business_id,user_id,action_type,entity_name,entity_id,new_data) values(p_business_id,actor,'updated','expense',p_expense_id,jsonb_build_object('total_amount_cents',p_total_amount_cents)); end $$;
create function public.delete_expense_draft(p_expense_id uuid,p_business_id uuid) returns void language plpgsql security definer set search_path='' as $$ declare actor uuid:=public.assert_expense_manager(p_business_id); e public.expenses; begin select * into e from public.expenses where id=p_expense_id and business_id=p_business_id for update; if not found then raise exception 'expense not found' using errcode='P0002'; end if; if e.status<>'draft' then raise exception 'draft required' using errcode='55000'; end if; if exists(select 1 from public.expense_documents where expense_id=p_expense_id) then raise exception 'remove documents first' using errcode='23514'; end if; insert into public.audit_logs(business_id,user_id,action_type,entity_name,entity_id,old_data) values(p_business_id,actor,'deleted','expense',p_expense_id,jsonb_build_object('reference',e.reference)); delete from public.expenses where id=p_expense_id; end $$;
create function public.validate_expense(p_expense_id uuid,p_business_id uuid) returns void language plpgsql security definer set search_path='' as $$ declare actor uuid:=public.assert_expense_manager(p_business_id); begin update public.expenses set status='validated',validated_at=now() where id=p_expense_id and business_id=p_business_id and status='draft'; if not found then raise exception 'draft required' using errcode='55000'; end if; insert into public.audit_logs(business_id,user_id,action_type,entity_name,entity_id,new_data) values(p_business_id,actor,'validated','expense',p_expense_id,'{"status":"validated"}'); end $$;
create function public.cancel_expense(p_expense_id uuid,p_business_id uuid,p_reason text) returns void language plpgsql security definer set search_path='' as $$ declare actor uuid:=public.assert_expense_manager(p_business_id); e public.expenses; paid bigint; refunded bigint; begin select * into e from public.expenses where id=p_expense_id and business_id=p_business_id for update; if not found or e.status<>'validated' then raise exception 'validated expense required' using errcode='55000'; end if; select coalesce(sum(amount_cents),0) into paid from public.expense_payments where expense_id=p_expense_id; select coalesce(sum(amount_cents),0) into refunded from public.expense_refunds where expense_id=p_expense_id; if paid-refunded<>0 then raise exception 'expense has non-zero net payment' using errcode='23514'; end if; update public.expenses set status='cancelled',cancelled_at=now(),cancellation_reason=btrim(p_reason) where id=p_expense_id; insert into public.audit_logs(business_id,user_id,action_type,entity_name,entity_id,new_data) values(p_business_id,actor,'cancelled','expense',p_expense_id,jsonb_build_object('reason',btrim(p_reason))); end $$;

create function public.record_expense_payment(p_expense_id uuid,p_business_id uuid,p_paid_on date,p_bank_debited_on date,p_amount_cents bigint,p_method public.expense_payment_method,p_external_reference text,p_notes text) returns uuid language plpgsql security definer set search_path='' as $$ declare actor uuid:=public.assert_expense_manager(p_business_id); e public.expenses; paid bigint; nid uuid:=gen_random_uuid(); bamt bigint; begin select * into e from public.expenses where id=p_expense_id and business_id=p_business_id for update; if not found or e.status<>'validated' then raise exception 'validated expense required' using errcode='55000'; end if; select coalesce(sum(amount_cents),0) into paid from public.expense_payments where expense_id=p_expense_id; if paid+p_amount_cents>e.total_amount_cents then raise exception 'payment exceeds expense total' using errcode='23514'; end if; bamt:=(p_amount_cents*e.professional_share_basis_points+5000)/10000; insert into public.expense_payments(id,business_id,expense_id,paid_on,bank_debited_on,amount_cents,business_amount_cents,method,external_reference,notes,created_by) values(nid,p_business_id,p_expense_id,p_paid_on,p_bank_debited_on,p_amount_cents,bamt,p_method,nullif(btrim(p_external_reference),''),nullif(btrim(p_notes),''),actor); insert into public.audit_logs(business_id,user_id,action_type,entity_name,entity_id,new_data) values(p_business_id,actor,'created','expense_payment',nid,jsonb_build_object('expense_id',p_expense_id,'amount_cents',p_amount_cents)); return nid; end $$;
create function public.record_expense_refund(p_expense_payment_id uuid,p_expense_id uuid,p_business_id uuid,p_received_on date,p_amount_cents bigint,p_kind public.expense_refund_kind,p_reason text,p_external_reference text) returns uuid language plpgsql security definer set search_path='' as $$ declare actor uuid:=public.assert_expense_manager(p_business_id); p public.expense_payments; refunded bigint; nid uuid:=gen_random_uuid(); e public.expenses; bamt bigint; begin select * into p from public.expense_payments where id=p_expense_payment_id and expense_id=p_expense_id and business_id=p_business_id for update; if not found then raise exception 'expense payment not found' using errcode='P0002'; end if; if p_received_on<p.paid_on then raise exception 'invalid refund date' using errcode='22023'; end if; select coalesce(sum(amount_cents),0) into refunded from public.expense_refunds where expense_payment_id=p_expense_payment_id; if refunded+p_amount_cents>p.amount_cents then raise exception 'refund exceeds available amount' using errcode='23514'; end if; select * into e from public.expenses where id=p_expense_id; bamt:=(p_amount_cents*e.professional_share_basis_points+5000)/10000; insert into public.expense_refunds(id,business_id,expense_id,expense_payment_id,received_on,amount_cents,business_amount_cents,kind,reason,external_reference,created_by) values(nid,p_business_id,p_expense_id,p_expense_payment_id,p_received_on,p_amount_cents,bamt,p_kind,btrim(p_reason),nullif(btrim(p_external_reference),''),actor); insert into public.audit_logs(business_id,user_id,action_type,entity_name,entity_id,new_data) values(p_business_id,actor,'created','expense_refund',nid,jsonb_build_object('expense_id',p_expense_id,'amount_cents',p_amount_cents)); return nid; end $$;

create function public.attach_expense_document(p_document_id uuid,p_expense_id uuid,p_business_id uuid,p_kind public.document_kind,p_storage_path text,p_original_name text,p_mime_type text,p_size_bytes bigint) returns uuid language plpgsql security definer set search_path='' as $$ declare actor uuid:=public.assert_expense_manager(p_business_id); lid uuid:=gen_random_uuid(); begin if not exists(select 1 from public.expenses where id=p_expense_id and business_id=p_business_id and status<>'cancelled') then raise exception 'expense not found' using errcode='P0002'; end if; if p_storage_path<>p_business_id::text||'/'||p_expense_id::text||'/'||p_document_id::text||'/'||regexp_replace(lower(p_original_name),'[^a-z0-9._-]+','-','g') then raise exception 'invalid storage path' using errcode='22023'; end if; insert into public.documents(id,business_id,kind,storage_bucket,storage_path,original_name,mime_type,size_bytes,uploaded_by) values(p_document_id,p_business_id,p_kind,'expense-documents',p_storage_path,p_original_name,p_mime_type,p_size_bytes,actor); insert into public.expense_documents(id,business_id,expense_id,document_id,attached_by) values(lid,p_business_id,p_expense_id,p_document_id,actor); insert into public.audit_logs(business_id,user_id,action_type,entity_name,entity_id,new_data) values(p_business_id,actor,'attached','document',p_document_id,jsonb_build_object('expense_id',p_expense_id)); return lid; end $$;
create function public.delete_draft_expense_document(p_document_id uuid,p_expense_id uuid,p_business_id uuid) returns void language plpgsql security definer set search_path='' as $$ declare actor uuid:=public.assert_expense_manager(p_business_id); s public.expense_status; begin select status into s from public.expenses where id=p_expense_id and business_id=p_business_id for update; if s is distinct from 'draft' then raise exception 'draft required' using errcode='55000'; end if; delete from public.expense_documents where document_id=p_document_id and expense_id=p_expense_id and business_id=p_business_id; if not found then raise exception 'document not found' using errcode='P0002'; end if; perform set_config('yrelcompta.allow_document_delete','on',true); delete from public.documents where id=p_document_id and business_id=p_business_id; insert into public.audit_logs(business_id,user_id,action_type,entity_name,entity_id) values(p_business_id,actor,'deleted','document',p_document_id); end $$;

create function public.create_recurring_expense_template(p_business_id uuid,p_supplier_id uuid,p_category public.expense_category,p_subcategory text,p_nature public.expense_nature,p_cost_behavior public.expense_cost_behavior,p_description text,p_estimated_amount_cents bigint,p_professional_share_basis_points integer,p_frequency public.recurrence_frequency,p_next_due_on date,p_notes text) returns uuid language plpgsql security definer set search_path='' as $$ declare actor uuid:=public.assert_expense_manager(p_business_id); nid uuid:=gen_random_uuid(); begin insert into public.recurring_expense_templates(id,business_id,supplier_id,category,subcategory,nature,cost_behavior,description,estimated_amount_cents,professional_share_basis_points,frequency,next_due_on,notes,created_by) values(nid,p_business_id,p_supplier_id,p_category,nullif(btrim(p_subcategory),''),p_nature,p_cost_behavior,btrim(p_description),p_estimated_amount_cents,p_professional_share_basis_points,p_frequency,p_next_due_on,nullif(btrim(p_notes),''),actor); insert into public.audit_logs(business_id,user_id,action_type,entity_name,entity_id,new_data) values(p_business_id,actor,'created','recurring_expense_template',nid,jsonb_build_object('description',btrim(p_description))); return nid; end $$;
create function public.update_recurring_expense_template(p_template_id uuid,p_business_id uuid,p_supplier_id uuid,p_category public.expense_category,p_nature public.expense_nature,p_cost_behavior public.expense_cost_behavior,p_description text,p_estimated_amount_cents bigint,p_professional_share_basis_points integer,p_frequency public.recurrence_frequency,p_next_due_on date,p_notes text,p_is_active boolean) returns void language plpgsql security definer set search_path='' as $$ declare actor uuid:=public.assert_expense_manager(p_business_id); begin update public.recurring_expense_templates set supplier_id=p_supplier_id,category=p_category,nature=p_nature,cost_behavior=p_cost_behavior,description=btrim(p_description),estimated_amount_cents=p_estimated_amount_cents,professional_share_basis_points=p_professional_share_basis_points,frequency=p_frequency,next_due_on=p_next_due_on,notes=nullif(btrim(p_notes),''),is_active=p_is_active where id=p_template_id and business_id=p_business_id; if not found then raise exception 'template not found' using errcode='P0002'; end if; insert into public.audit_logs(business_id,user_id,action_type,entity_name,entity_id,new_data) values(p_business_id,actor,'updated','recurring_expense_template',p_template_id,jsonb_build_object('is_active',p_is_active)); end $$;
create function public.archive_recurring_expense_template(p_template_id uuid,p_business_id uuid) returns void language plpgsql security definer set search_path='' as $$ declare actor uuid:=public.assert_expense_manager(p_business_id); begin update public.recurring_expense_templates set is_active=false where id=p_template_id and business_id=p_business_id; if not found then raise exception 'template not found' using errcode='P0002'; end if; insert into public.audit_logs(business_id,user_id,action_type,entity_name,entity_id) values(p_business_id,actor,'archived','recurring_expense_template',p_template_id); end $$;
create function public.create_expense_from_recurring_template(p_template_id uuid,p_business_id uuid,p_purchased_on date) returns uuid language plpgsql security definer set search_path='' as $$ declare actor uuid:=public.assert_expense_manager(p_business_id); t public.recurring_expense_templates; eid uuid; nextdate date; begin select * into t from public.recurring_expense_templates where id=p_template_id and business_id=p_business_id and is_active for update; if not found then raise exception 'active template not found' using errcode='P0002'; end if; eid:=public.create_expense_draft(p_business_id,p_purchased_on,t.next_due_on,t.supplier_id,t.category,t.subcategory,t.nature,t.cost_behavior,t.description,null,t.estimated_amount_cents,t.professional_share_basis_points,t.notes); nextdate:=case t.frequency when 'monthly' then (t.next_due_on+interval '1 month')::date when 'quarterly' then (t.next_due_on+interval '3 months')::date else (t.next_due_on+interval '1 year')::date end; update public.recurring_expense_templates set last_generated_on=p_purchased_on,next_due_on=nextdate where id=p_template_id; insert into public.audit_logs(business_id,user_id,action_type,entity_name,entity_id,new_data) values(p_business_id,actor,'generated','recurring_expense_template',p_template_id,jsonb_build_object('expense_id',eid)); return eid; end $$;

revoke all on function public.protect_expense_mutations(),public.prevent_expense_financial_mutation(),public.prevent_document_mutation(),public.protect_expense_document_delete() from public;
revoke all on function public.create_supplier(uuid,text,text,text,text,text,text,text,text,text,text,text),public.update_supplier(uuid,uuid,text,text,text,text,text,boolean),public.archive_supplier(uuid,uuid),public.create_expense_draft(uuid,date,date,uuid,public.expense_category,text,public.expense_nature,public.expense_cost_behavior,text,text,bigint,integer,text),public.update_expense_draft(uuid,uuid,date,date,uuid,public.expense_category,text,public.expense_nature,public.expense_cost_behavior,text,text,bigint,integer,text),public.delete_expense_draft(uuid,uuid),public.validate_expense(uuid,uuid),public.cancel_expense(uuid,uuid,text),public.record_expense_payment(uuid,uuid,date,date,bigint,public.expense_payment_method,text,text),public.record_expense_refund(uuid,uuid,uuid,date,bigint,public.expense_refund_kind,text,text),public.attach_expense_document(uuid,uuid,uuid,public.document_kind,text,text,text,bigint),public.delete_draft_expense_document(uuid,uuid,uuid),public.create_recurring_expense_template(uuid,uuid,public.expense_category,text,public.expense_nature,public.expense_cost_behavior,text,bigint,integer,public.recurrence_frequency,date,text),public.update_recurring_expense_template(uuid,uuid,uuid,public.expense_category,public.expense_nature,public.expense_cost_behavior,text,bigint,integer,public.recurrence_frequency,date,text,boolean),public.archive_recurring_expense_template(uuid,uuid),public.create_expense_from_recurring_template(uuid,uuid,date) from public;
grant execute on function public.create_supplier(uuid,text,text,text,text,text,text,text,text,text,text,text),public.update_supplier(uuid,uuid,text,text,text,text,text,boolean),public.archive_supplier(uuid,uuid),public.create_expense_draft(uuid,date,date,uuid,public.expense_category,text,public.expense_nature,public.expense_cost_behavior,text,text,bigint,integer,text),public.update_expense_draft(uuid,uuid,date,date,uuid,public.expense_category,text,public.expense_nature,public.expense_cost_behavior,text,text,bigint,integer,text),public.delete_expense_draft(uuid,uuid),public.validate_expense(uuid,uuid),public.cancel_expense(uuid,uuid,text),public.record_expense_payment(uuid,uuid,date,date,bigint,public.expense_payment_method,text,text),public.record_expense_refund(uuid,uuid,uuid,date,bigint,public.expense_refund_kind,text,text),public.attach_expense_document(uuid,uuid,uuid,public.document_kind,text,text,text,bigint),public.delete_draft_expense_document(uuid,uuid,uuid),public.create_recurring_expense_template(uuid,uuid,public.expense_category,text,public.expense_nature,public.expense_cost_behavior,text,bigint,integer,public.recurrence_frequency,date,text),public.update_recurring_expense_template(uuid,uuid,uuid,public.expense_category,public.expense_nature,public.expense_cost_behavior,text,bigint,integer,public.recurrence_frequency,date,text,boolean),public.archive_recurring_expense_template(uuid,uuid),public.create_expense_from_recurring_template(uuid,uuid,date) to authenticated;

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('expense-documents','expense-documents',false,10485760,array['application/pdf','image/jpeg','image/png','image/webp','image/heic','image/heif']) on conflict(id) do update set public=false,file_size_limit=excluded.file_size_limit,allowed_mime_types=excluded.allowed_mime_types;
create policy expense_documents_storage_select on storage.objects for select to authenticated using (bucket_id='expense-documents' and public.is_business_member((storage.foldername(name))[1]::uuid));
create policy expense_documents_storage_insert on storage.objects for insert to authenticated with check (bucket_id='expense-documents' and public.can_manage_business((storage.foldername(name))[1]::uuid) and exists(select 1 from public.expenses e where e.business_id=(storage.foldername(name))[1]::uuid and e.id=(storage.foldername(name))[2]::uuid and e.status<>'cancelled'));
create policy expense_documents_storage_delete on storage.objects for delete to authenticated using (bucket_id='expense-documents' and public.can_manage_business((storage.foldername(name))[1]::uuid) and exists(select 1 from public.expenses e join public.expense_documents ed on ed.expense_id=e.id and ed.business_id=e.business_id join public.documents d on d.id=ed.document_id and d.business_id=e.business_id where e.business_id=(storage.foldername(name))[1]::uuid and e.id=(storage.foldername(name))[2]::uuid and e.status='draft' and d.storage_path=name));

comment on table public.expenses is 'Dépenses : brouillons modifiables, écritures validées immuables et annulation contrôlée.';
comment on table public.documents is 'Métadonnées immuables de justificatifs privés, sans URL publique permanente.';
